name: Quant Edge Backtest and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-backtest:
    runs-on: ubuntu-latest  # Cloud-based Ubuntu runner (free)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run unit tests
      run: |
        pytest tests/ -v  # Verbose output for logs

    - name: Run backtest
      run: |
        python main.py  # Outputs metrics to console (visible in logs)

    - name: Upload logs as artifact (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: backtest-logs
        path: |
          *.log
          logs/  # If generated
